AllCops:
  Exclude:
    - 'Guardfile'
    - 'Rakefile'
    - 'db/schema.rb'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'bin/*'
  NewCops: enable
  TargetRubyVersion: 2.6
Style/Documentation:
  Enabled: false
Layout/LineLength:
  Enabled: false
Style/RescueModifier:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Max: 100
Metrics/ClassLength:
  Max: 200
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/ModuleLength:
  Max: 200
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'faithlife.gemspec'
